// Copyright (C) 2024 T-Force I/O
// This file is part of TF Unifiler
//
// TF Unifiler is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// TF Unifiler is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with TF Unifiler. If not, see <https://www.gnu.org/licenses/>.

package checksum

import (
	"strings"
	"testing"

	"github.com/tforceaio/tf-unifiler-go/xlib"
)

func TestPParseCRC32ItemCount(t *testing.T) {
	var tests = []struct {
		name    string
		content string
		count   int
	}{
		{"0 item", "", 0},
		{"comment only", "; generated by QuickSFV", 0},
		{"1 item", "go.mod a1b2c3d4", 1},
		{"2 items", "go.mod a1b2c3d4\ngo.sum e5f6a7b8", 2},
		{"CRLF", "go.mod a1b2c3d4\r\ngo.sum e5f6a7b8", 2},
		{"comment skipped", "; comment\ngo.mod a1b2c3d4", 1},
		{"empty line skipped", "\ngo.mod a1b2c3d4", 1},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			items, err := ParseCRC32(strings.NewReader(tt.content))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if len(items) != tt.count {
				t.Errorf("Invalid number of items. Expected %d. Actual %d.", tt.count, len(items))
			}
		})
	}
}

func TestParseCRC32Syntax(t *testing.T) {
	var tests = []struct {
		name    string
		content string
		path    string
		hash    string
	}{
		{"simple", "go.mod a1b2c3d4", "go.mod", "a1b2c3d4"},
		{"path with directory", "filesystem/file.go a1b2c3d4", "filesystem/file.go", "a1b2c3d4"},
		{"path with space", "file system/file.go a1b2c3d4", "file system/file.go", "a1b2c3d4"},
		{"uppercase hash", "go.mod A1B2C3D4", "go.mod", "A1B2C3D4"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			items, err := ParseCRC32(strings.NewReader(tt.content))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			item := items[0]
			if item.Path != tt.path {
				t.Errorf("Wrong path. Expected '%s'. Actual '%s'.", tt.path, item.Path)
			}
			if item.Hash != tt.hash {
				t.Errorf("Wrong hash. Expected '%s'. Actual '%s'.", tt.hash, item.Hash)
			}
		})
	}
}

func TestParseCRC32Error(t *testing.T) {
	var tests = []struct {
		name    string
		content string
		err     string
	}{
		{"hash only", "a1b2c3d4", "invalid token. expected hash actual ''"},
		{"invalid crc32 (too short)", "go.mod a1b2c3", "invalid CRC32 hash 'a1b2c3'"},
		{"invalid crc32 (too long)", "go.mod a1b2c3d4e5", "invalid CRC32 hash 'a1b2c3d4e5'"},
		{"invalid crc32 character", "go.mod a1b2c3XY", "invalid CRC32 hash 'a1b2c3XY'"},
		{"missing path", " a1b2c3d4", "invalid token. expected path actual ' '"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := ParseCRC32(strings.NewReader(tt.content))
			errs := xlib.ErrString(err)
			if errs != tt.err {
				t.Errorf("wrong error. Expected %q. Actual %q.", tt.err, errs)
			}
		})
	}
}
